name: arru-seismic

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python>=3.6
  - anaconda
  - pip
  - matplotlib
  - pandas
  - numpy 
  - pip:
    - obspy=1.1.0
    - tensorflow-gpu=2.4.0
    - tensorflow-addons=0.11.2
