name: arru-seismic

channels:
  - conda-forge
  - defaults
  
dependencies:
  - python>=3.6
  - anaconda
  - pip
  - matplotlib
  - pandas
  - numpy     
  - tensorflow-gpu=2.4
  - tensorflow-addons
  - pip:
    - obspy=1.1.0

